apiVersion: apps/v1
kind: Deployment
metadata:
  name: deletetask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deletetask-api
  template:
    metadata:
      labels:
        app: deletetask-api
    spec:
      containers:
      - name: deletetask-api
        image: todoappacr2213.azurecr.io/deletetask:v1
        ports:
        - containerPort: 8000
