apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ui-ingress
  labels:
    app.kubernetes.io/name: todo-ui-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: deletetask.devopsai.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: deletetask-api-svc
            port: 
              number: 80
